em540_master:
  host: 192.168.102.240
  port: 8899
  slave_id: 1
  update_interval: 0.1
  timeout: 0.15
  retries: 0
  log_level: INFO

em540_slave:
  host: 0.0.0.0
  rtu_port: 5002
  tcp_port: 5001
  slave_id: 1
  update_timeout: 0.5
  log_level: INFO

ts65a_slave:
  host: 0.0.0.0
  port: 5003
  slave_id: 1
  update_timeout: 0.5
  grid_feed_in_hard_limit: -5000
  smoothing_num_points: 20
  log_level: INFO

mqtt:
  enabled: true
  host: localhost
  port: 1883
  username: ""
  password: ""
  update_interval: 0.5
  log_level: INFO

pymodbus:
  log_level: INFO

root:
    log_level: INFO
