services:
  em540-bridge:
    image: lerebel103/em540-bridge:latest
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    container_name: em540-bridge
    stdin_open: true
    privileged: false
    tty: true
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/em540-bridge/config.yaml
    environment:
      - TZ="Australia/Perth"
    ports:
      - 5002:5002
      - 5003:5003
      - 5004:5004
    #devices:
        # Adjust according to your setup, if using a USB to RS485 adapter
        #- /dev/ttyUSB0:/dev/ttyUSB0


